### ISSUE TITLE
[Candidate 4v4 Wastelands Dust ZH v4] Audio emitters have no easing and crackle when scrolling over

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#565] opened 2023-12-31 10:44 UTC
## Observed behavior

Audio emitters have no easing and crackle when scrolling over.

## Expected behavior

Audio emitters ease in and out when scrolling over. Ambient sound does not crackle.

## Videos

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b0cf3641-aea5-4002-a879-b009e4ae06d1

**Comment by toirehantaa** [comment] 2024-01-08 11:16
fixed

**Comment by xezon** [comment] 2024-01-20 12:20
Wind is much quieter now, but the crackling is still audible in principle.

**Comment by xezon** [comment] 2024-01-27 12:42
Audio is still crackling on my machine.

**Comment by toirehantaa** [comment] 2024-01-27 15:04
not finding another fix tbh. I think this is minimal and neglectable anyways. As long as you are not scrolling super fast and really paying attention, no one will notice for sure

**Comment by toirehantaa** [comment] 2024-02-01 12:54
NoMerci has found the cause for this apparently. Giving you the fixed one

**Comment by xezon** [comment] 2024-02-03 16:52
The new map I received looks like an old version of the map. It has the bugged houses again. And rocks by the Supply Dock's are missing. When editing a map, it is important to get latest version from GitHub, otherwise other changes will be undone when editing another map version.

I will reject the new edit.

Note: Wind audio was ok, but there is a strange fire sound at the ruins.

![shot_20240203_174947_1](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/9e3f7b91-2ed7-43e7-9aa2-a52ffcdb388e)

**Comment by xezon** [comment] 2024-03-23 13:54
Not sure what to think of the audio. Wind is quieter now, but the crackling is still there in principle. Is obvious when significantly raising the local audio volume. Opinions?

**Comment by xezon** [comment] 2024-05-04 06:44
Any opinions?

**Comment by xezon** [comment] 2024-05-15 18:12
Any opinions?

**Comment by toirehantaa** [comment] 2024-05-17 21:23
I'd just say leave as is then

**Comment by Jundiyy** [comment] 2024-05-18 00:37
If you want, I can give it a shot, can't promise qhow good it'll be but happy to help.

**Comment by Jundiyy** [comment] 2024-05-21 21:38
[Wastelands Dust ZH v4.zip](https://github.com/TheSuperHackers/GeneralsRankedMaps/files/15395648/Wastelands.Dust.ZH.v4.zip)
Does this help?
I didn't look for any hidden sounds.

**Comment by xezon** [comment] 2024-05-22 17:48
Sounds bad. Not sure if worse than before, but I will reject that edit.

**Comment by Jundiyy** [comment] 2024-05-22 19:34
Do you have the version which you said was better but rejected due to it not being the latest? I can look at the sounds from there.

**Comment by xezon** [comment] 2024-05-22 19:38
The latest version is here in github repo.

**Comment by Jundiyy** [comment] 2024-05-22 19:58
> The new map I received looks like an old version of the map. It has the bugged houses again. And rocks by the Supply Dock's are missing. When editing a map, it is important to get latest version from GitHub, otherwise other changes will be undone when editing another map version.
> 
> I will reject the new edit.
> 
> Note: Wind audio was ok, but there is a strange fire sound at the ruins.
> 
> ![shot_20240203_174947_1](https://private-user-images.githubusercontent.com/4720891/302049263-9e3f7b91-2ed7-43e7-9aa2-a52ffcdb388e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MDgxMzEsIm5iZiI6MTcxNjQwNzgzMSwicGF0aCI6Ii80NzIwODkxLzMwMjA0OTI2My05ZTNmN2I5MS0yZWQ3LTQzZTctOWFhMi1hNTJmZmNkYjM4OGUuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjJUMTk1NzExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzRkMDVjZWQwNjUyNWFkYzM2MmU3NzliMDA4NTE3YmFmODI4YWJlZGE3ZGI5MWM1ZDY2MmMzMzcwNjgyOGU1MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3qFBV01NTjuZsY0o4zHXqM7amkhZmodX5EZ3PHfmJV8)

I am referring to this version, I can check the settings.

**Comment by xezon** [comment] 2024-05-22 20:07
I suggest check with NoMerci.

**Comment by xezon** [comment] 2024-07-03 17:03
### 03.07.2024

Crackling is mostly gone. Easing is not perfect, but acceptable.

**Closed** 2024-07-07 12:09 UTC
Labels: blocker, audio
